# Generated by Django 5.1.3 on 2024-12-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundedFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('amount_funded', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_funded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
